name: README

on:
  # Run manually when needed
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max_old_space_size=6144

jobs:
  update-readme:
    name: Update & PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install dependencies
        shell: bash
        run: pnpm install
      - name: Update README
        run: pnpm run readme
      - name: Check for changes
        id: changes
        run: |
          git add .
          if git diff-index --quiet HEAD --; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update readme.md and issue templates
          title: 'Update extension list in readme'
          body: |
            Auto-generated update from `pnpm run readme`

            - Updates extension table in readme.md
            - Updates issue templates with current extensions
          branch: chore/update-readme
          delete-branch: true
